# Do not delete lines which have [text]
# Other lines are needed to change as user needs

[User]
name = MAPS Technologies
address1 = 57 Yashoda Marg
address2 = Officers Campus Ext
address3 = Sirsi Road
address4 = Jaipur - 302012
address5 = Rajasthan, India

[Geocode]
Location = 26°55'11"N 75°47'16"E (IP approx)
